version: '3'

services:
    task_3:
        image: node:latest
        working_dir: /json_servak
        volumes:
        - ./:/json_servak
        command: bash script_pipe.sh

    nginx:
        image: nginx
        ports:
        - "8080:80"
        environment:
        - NGINX_HOST=0.0.0.0
        - NGINX_PORT=80
        
        links: 
        - task_3
       


       